name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps
    
    - name: Run Playwright tests
      run: |
        pytest tests/ -v --html=playwright-report/report.html --self-contained-html
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()  # Upload even if tests fail
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test recordings
      uses: actions/upload-artifact@v4
      if: always()  # Upload even if tests fail
      with:
        name: test-recordings
        path: test-results/
        retention-days: 30
    
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: html-report
        path: playwright-report/report.html
        retention-days: 30
